### ISSUE TITLE
Multi-arch doesn't work in GitlabCI

### ISSUE THREAD

**Issue by Decipher** [drevops/mariadb-drupal-data#17]
I have a GitlabCI job that uses the `seed-db.sh` script, and it errors with the following message:

```
[INFO] Stage 2: Build image
[TASK] Build image [REDACTED]/db:latest for linux/amd64,linux/arm64 platform(s).
error: multiple platforms feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
```

I had previously used this script for another project, but I can also see that in between this two implementations there has been changes to add multi-arch support to the script.

To workaround I had to specify a single arch using `DESTINATION_PLATFORMS=...`

**Comment by AlexSkrypnyk** [comment]
@Decipher 
thank you for reporting this. I will try to look into this shortly.

Could you please provide a little bit more information about the runner container in GitLab: arch, OS, version etc. The CI for this project uses CircleCI with own custom runner (`drevops/ci-builder`), which is based on official php Docker image which is Debian.

I may be able to replicate the issue you are experiencing if I can add another runner container to the CircleCI CI pipeline to test cross-OS and cross-platform.

**Comment by AlexSkrypnyk** [comment]
In order to make the multi-arch build work in CircleCI (to run tests, including seeding, there were additional steps added: https://github.com/drevops/mariadb-drupal-data/blob/main/.circleci/config.yml#L19

Maybe you need to add similar step to your GitLab setup.
